// svelte/src/App.svelte
<script lang="ts">
  import { hasRegisteredName, messages, toasts, socket, name } from "./stores";
  import { afterUpdate, onMount } from "svelte";
  import Login from "./lib/login.svelte";
  import { sendMessage } from "./utility-functions";
  import Button from "./lib/button.svelte";
  import Input from "./lib/input.svelte";
  import ChatMessage from "./lib/chat-message.svelte";
  import Toasts from "./lib/toasts.svelte";
  import { ToastType } from "./interfaces";
  import { v4 as uuidv4 } from "uuid";
  import { TOAST_DURATION } from "./constants";

  let message = "";
  let chatWindow: HTMLUListElement | null = null;

  afterUpdate(() => {
    if (chatWindow) {
      chatWindow.scrollTo(0, chatWindow.scrollHeight);
    }
  });

  onMount(async () => {
    if ($socket != null) return;

    let newSocket = new WebSocket("ws://127.0.0.1:8080/ws");

    newSocket.onopen = function (this: WebSocket, ev: Event) {
      console.log("Connected");
    };

    newSocket.onclose = function () {
      console.log("Disconnected");
      $socket = null;
    };

    newSocket.onmessage = function (res: MessageEvent<any>) {
      console.log("res.data", res.data);

      let serverMsg = JSON.parse(res.data);

      switch (serverMsg.msg_type) {
        case "AllMessages":
          $messages = serverMsg.data;
          break;
        case "NewMessage":
          $messages = [...$messages, serverMsg.data];
          break;
        case "NameTaken":
          let item = {
            type: ToastType.Client,
            message: "Name has already been taken.",
            uuid: uuidv4(),
          };
          toasts.add(item);
          setTimeout(() => {
            toasts.remove(item);
          }, TOAST_DURATION);
          $hasRegisteredName = false;
          break;
        case "NameRegistered":
          console.log("Name registered");
          $hasRegisteredName = true;
          break;
        case "Joined":
          $messages = [
            ...$messages,
            { name: serverMsg.data, message: "Hello, world!" },
          ];
          break;
      }

      console.log("messages", $messages);
    };

    $socket = newSocket;
  });

  function onSubmit(e) {
    e.preventDefault();
    if ($socket == null) {
      console.log("Socket is null");
      return;
    }

    if (message.trim() === "") {
      console.log("Message was empty.");
      return;
    }

    sendMessage({ msg_type: "Chat", data: { name: $name, message } });
    message = "";
  }
</script>

<main class="flex h-screen overflow-hidden bg-zinc-50">
  <Toasts />
  {#if !$hasRegisteredName}
    <Login />
  {:else}
    <div class="grid grid-cols-1 grid-rows-2 m-auto h-4/5 w-4/5 gap-2">
      <ul
        class="overflow-y-scroll p-4 border rounded-lg bg-white"
        bind:this={chatWindow}
      >
        {#each $messages as msg}
          <li><ChatMessage chatMsg={msg} /></li>
        {/each}
      </ul>

      <form class="flex flex-col" on:submit={onSubmit}>
        <Input
          classes="mb-2"
          label="Enter message"
          id="chat-message"
          bind:value={message}
        />
        <Button classes="w-fit" id="send-message" value="Send" />
      </form>
    </div>
  {/if}
</main>

<style>
</style>

// vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUpdated, type Ref } from 'vue'
import { useHasRegisteredNameStore, useMessagesStore, useNameStore, useSocketStore, useToastsStore } from '@/stores'
import Login from './components/Login.vue'
import Input from './components/Input.vue'
import ChatMessage from './components/ChatMessage.vue'
import { ToastType } from './interfaces';
import { v4 as uuidv4 } from "uuid";

let message = ref("");
let ul: Ref<HTMLUListElement | null> = ref(null);

const messages = useMessagesStore();
const socket = useSocketStore();
const toasts = useToastsStore();
const name = useNameStore();
const hasRegisteredName = useHasRegisteredNameStore();

onUpdated(() => {
  ul.value?.scrollTo(0, ul.value.scrollHeight);
})

onMounted(() => {
    if (socket.socket != null) return;

    let newSocket = new WebSocket("ws://127.0.0.1:8080/ws");

    newSocket.onopen = function (this: WebSocket, ev: Event) {
      console.log("Connected");
    };

    newSocket.onclose = function () {
      console.log("Disconnected");
      socket.socket = null;
    };

    newSocket.onmessage = function (res: MessageEvent<any>) {
      console.log("res.data", res.data);

      let serverMsg = JSON.parse(res.data);

      switch (serverMsg.msg_type) {
        case "AllMessages":
          messages.messages = serverMsg.data;
          break;
        case "NewMessage":
          messages.messages = [...messages.messages, serverMsg.data];
          break;
        case "NameTaken":
          let item = {
            type: ToastType.Client,
            message: "Name has already been taken.",
            uuid: uuidv4(),
          };
          toasts.add(item);
          hasRegisteredName.hasRegisteredName = false;
          break;
        case "NameRegistered":
          console.log("Name registered");
          hasRegisteredName.hasRegisteredName = true;
          break;
        case "Joined":
          messages.messages = [
            ...messages.messages,
            { name: serverMsg.data, message: "Hello, world!" },
          ];
          break;
      }

      console.log("messages", messages.messages);
    };

    socket.socket = newSocket;
  });

  function onSubmit(e: any) {
    e.preventDefault();
    if (socket.socket == null) {
      console.log("Socket is null");
      return;
    }

    if (message.value.trim() === "") {
      console.log("Message was empty.");
      return;
    }

    socket.sendMessage({ msg_type: "Chat", data: { name: name.name, message: message.value } });
    message.value = "";
  }

</script>

<template>
<main class="flex h-screen overflow-hidden bg-zinc-50">
  <!-- <Toasts /> -->
    <Login v-if="!hasRegisteredName.hasRegisteredName"/>
    <div v-else class="grid grid-cols-1 grid-rows-2 m-auto h-4/5 w-4/5 gap-2">
      <ul
        class="overflow-y-scroll p-4 border rounded-lg bg-white"
        ref="ul"
      >
          <li v-for="msg in messages.messages"><ChatMessage :chatMsg="msg" /></li>
      </ul>

      <form class="flex flex-col" @submit="onSubmit">
        <Input
          classes="mb-2"
          label="Enter message"
          id="chat-message"
          v-model="message"
        />
        <input type="submit" classes="w-fit" id="send-message" value="Send" />
      </form>
    </div>
</main>
</template>

<style scoped>
</style>
